name: DAST Security Scan

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: devsecops-demo
        run: pip install -r requirements.txt

      - name: Start FastAPI application
        working-directory: devsecops-demo
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Basic DAST - Check Security Headers
        run: |
          echo "=== DAST: Security Headers Check ==="
          curl -I http://localhost:8000
          
          echo ""
          echo "=== DAST: Testing API Endpoints ==="
          curl -v http://localhost:8000/
          curl -v http://localhost:8000/items/1?q=test
          
          echo ""
          echo "=== DAST: Checking for Common Vulnerabilities ==="
          
          # Check for missing security headers
          response=$(curl -s -I http://localhost:8000)
          
          echo "Checking X-Content-Type-Options header..."
          if echo "$response" | grep -q "x-content-type-options"; then
            echo "✓ X-Content-Type-Options header present"
          else
            echo "✗ FINDING: Missing X-Content-Type-Options header (Security risk)"
          fi
          
          echo "Checking X-Frame-Options header..."
          if echo "$response" | grep -q "x-frame-options"; then
            echo "✓ X-Frame-Options header present"
          else
            echo "✗ FINDING: Missing X-Frame-Options header (Clickjacking risk)"
          fi
          
          echo "Checking Strict-Transport-Security header..."
          if echo "$response" | grep -q "strict-transport-security"; then
            echo "✓ HSTS header present"
          else
            echo "✗ FINDING: Missing Strict-Transport-Security header (MITM risk)"
          fi
